version: '3.8'
services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes: 
      - ./:/app
      - /app/node_modules
    env_file: 
      - ./.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

